### ISSUE TITLE
Ubuntu 14.04 desktop i386 installation error on i7 netbook

### ISSUE THREAD

**Issue by LukeL99** [barrysteyn/node-scrypt#43]
I'm having issues installing this package on Ubuntu 14.04 on my Lenovo Yoga 2 Pro. Here's what I believe to be the relevant portion of the error:

  CC(target) Release/obj.target/scrypt_wrapper/src/util/salt.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  AR(target) Release/obj.target/scrypt_wrapper.a
  COPY Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.o
In file included from ../scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.c:34:0:
/usr/lib/gcc/i686-linux-gnu/4.8/include/emmintrin.h:31:3: error: #error "SSE2 instruction set not enabled"
 # error "SSE2 instruction set not enabled"
   ^
../scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.c:47:23: error: unknown type name ‘__m128i’
 static void salsa20_8(__m128i *);

[MORE STACK TRACE]

make: *** [Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.o] Error 1

Software versions:

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.8/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-i386 --with-arch-directory=i386 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-targets=all --enable-multiarch --disable-werror --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 

python --version
Python 2.7.6

node --version
v0.10.26

node-gyp --version
v0.13.0

If there's anything else I can do to help track down the issue, please let me know.

Thanks,

Luke

**Comment by 501st-alpha1** [comment]
I had this problem too. My CPU supports SSE, but it isn't enabled by default. Apparently [GCC doesn't enable SSE by default for i386 CPUs](http://gcc.gnu.org/onlinedocs/gcc-4.7.2/gcc/i386-and-x86_002d64-Options.html#index-mfpmath-1397).

To fix this, I did `export CFLAGS="-msse2"` before running the build command, and after that it worked.

**Comment by barrysteyn** [comment]
I just want to add something here. This is a very common problem that people are having. To alleviate this problem, I am going to be adding a way to manually enable or disable SSE2. Thanks @501st-alpha1 for the tip - I can make this even easier to use now.

**Comment by barrysteyn** [comment]
@501st-alpha1  Please can I ask your help: I am now detecting architecture and setting the appropriate flag. Actually, I am setting "-march=native" which should activate the necessary flags. I have pushed this change to a branch called *correct-flags-for-sse* - can you please get that branch and try rebuild the module without setting the environment variable and tell me if it works. In fact, if anyone who is listening on this issue can also do this and report here, I would be grateful.

Thanks in advance.

**Comment by barrysteyn** [comment]
This issue should be resolved now. I am adding the flag -march=native, which should automatically detect and use SSE if available.

**Comment by 501st-alpha1** [comment]
I cloned the repo and switched to branch `correct-flags-for-sse`, then ran `node-gyp configure build`. This is the output I got (not sure how much is relevant, so I'll post all of it):

    gyp info it worked if it ends with ok
    gyp info using node-gyp@1.0.2
    gyp info using node@0.10.36 | linux | ia32
    gyp info spawn python
    gyp info spawn args [ '[snip]/nvm/v0.10.36/lib/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '[snip]/node-scrypt/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '[snip]/nvm/v0.10.36/lib/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '[snip]/.node-gyp/0.10.36/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=[snip]/.node-gyp/0.10.36',
    gyp info spawn args   '-Dmodule_root_dir=[snip]/node-scrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    Traceback (most recent call last):
      File "[snip]/nvm/v0.10.36/lib/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
        sys.exit(gyp.script_main())
      File "[snip]/nvm/v0.10.36/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 534, in script_main
        return main(sys.argv[1:])
      File "[snip]/nvm/v0.10.36/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 527, in main
        return gyp_main(args)
      File "[snip]/nvm/v0.10.36/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 503, in gyp_main
        options.circular_check)
      File "[snip]/nvm/v0.10.36/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
        params['parallel'], params['root_targets'])
      File "[snip]/nvm/v0.10.36/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2692, in Load
        variables, includes, depth, check, True)
      File "[snip]/nvm/v0.10.36/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 388, in LoadTargetBuildFile
        build_file_data, PHASE_EARLY, variables, build_file_path)
      File "[snip]/nvm/v0.10.36/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1159, in ProcessVariablesAndConditionsInDict
        variables, build_file, 'variables')
      File "[snip]/nvm/v0.10.36/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1211, in ProcessVariablesAndConditionsInDict
        ProcessConditionsInDict(the_dict, phase, variables, build_file)
      File "[snip]/nvm/v0.10.36/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1088, in ProcessConditionsInDict
        variables, build_file)
      File "[snip]/nvm/v0.10.36/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1143, in ProcessVariablesAndConditionsInDict
        LoadAutomaticVariablesFromDict(variables, the_dict)
      File "[snip]/nvm/v0.10.36/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1096, in LoadAutomaticVariablesFromDict
        for key, value in the_dict.iteritems():
    AttributeError: 'str' object has no attribute 'iteritems' while trying to load binding.gyp
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit ([snip]/nvm/v0.10.36/lib/node_modules/node-gyp/lib/configure.js:343:16)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Linux 3.2.0-4-686-pae
    gyp ERR! command "node" "[snip]/nvm/v0.10.36/bin/node-gyp" "configure" "build"
    gyp ERR! cwd [snip]/node-scrypt
    gyp ERR! node -v v0.10.36
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok

**Comment by barrysteyn** [comment]
hi @501st-alpha1 

Two things:

1. The branch you tried is no longer relevant. I forgot to delete it, please can you try with the master branch
2. Ensure that you have python 2.7 installed, and that you are not using python 3 for node-gyp. node-gyp does not work with python version 3 (ignore this advice if you are not using python version 3).

Please can you try again and report back. I have removed that branch now...

**Comment by 501st-alpha1** [comment]
1. No problem.
2. I confirmed that I am using Python 2.7.3. (That is the output of `python -V`.)

When I tried the build again from `master`, this was the last few lines of output:

      CXX(target) Release/obj.target/scrypt/scrypt_node.o
    ../scrypt_node.cc:28:17: fatal error: nan.h: No such file or directory
    compilation terminated.
    make: *** [Release/obj.target/scrypt/scrypt_node.o] Error 1
    make: Leaving directory `[snip]/node-scrypt/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit ([snip]/nvm/v0.10.36/lib/node_modules/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Linux 3.2.0-4-686-pae
    gyp ERR! command "node" "[snip]/nvm/v0.10.36/bin/node-gyp" "configure" "build"
    gyp ERR! cwd [snip]/node-scrypt
    gyp ERR! node -v v0.10.36
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok

**Comment by barrysteyn** [comment]
Okay, you first need to install nan if you are going to compile it from source. So here are the instructions to get it going:
 1. Clone the master branch
 2. Go to the cloned folder, type: `npm install` (this will install all dependencies, including nan)
 3. Then rebuild: `node-gyp rebuild`

This should work. If that works, then try for the tests. Type `npm test`. If all those pass, then go for glory: Try install the module with npm directly: `npm install scrypt` (this should resolve all dependencies automatically).

Please report back.

**Comment by 501st-alpha1** [comment]
Success! Following your instructions, the build succeeded without error (including a separate run of `npm install scrypt`). Also, all tests passed. Thanks!

**Comment by barrysteyn** [comment]
Excellent. Then I will assume that this issue is solved :+1:

**Comment by pcordes** [comment]
I stumbled across this while trying to find out if i386 Ubuntu built packages with SSE2 enabled or not.

If you're compiling binaries to be used on the machine where you're compiling, **use `-O3 -march=native`** to enable everything your CPU has, and set `-mtune` appropriately for your CPU.  (Unless your CPU is too new for your gcc to know about it specifically, in which case you still get `-mtune=generic`)

Apparently i386 Ubuntu's gcc assumes a baseline instruction set that doesn't include SSE2, which I guess is good because why would you use 32-bit Ubuntu unless you were on a CPU too old for x86-64.

(x86-64 has SSE2 as a baseline part of the architecture, so 64-bit binaries can always assume SSE2 support, and thus gcc of course enables `-msse2` by default with `-m64`.)
